### ISSUE TITLE
Code auto formatter

### ISSUE THREAD

**Issue by SiAdcock** [guardian/fontastique#3]
What are people's opinions on auto-formatters? Coming into Elm from the cold, I like the idea of having a tool pretty up my code to make it fit with Elm's style and conventions.

[`elm-format`](https://github.com/avh4/elm-format) looks like a good starting place with wide editor support.

Any others?

cc @adamnfish @JamieB-gu @janua @faresite

**Comment by faresite** [comment]
One formatter to rule them all .. not sure any others exist, but it's the official way to go and I love that this decision is already made for me.

**Comment by adamnfish** [comment]
`elm-format` for sure. Its killer feature is that it has no configuration options 🎉
