### ISSUE TITLE
Android and iOS Support

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/fontastique#5]
Include an extra step on the sidebar for choosing which platforms to target. Possibly include the output for each platform in a [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element.

The fonts can then be downloaded for bundling in the app, as described in #6.

## Android

Android can read fonts from an [XML file](https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml).

## iOS

Custom fonts are added to the [`Info.plist`](https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app).

**Comment by JamieB-gu** [comment]
@jordanterry

**Comment by jordanterry** [comment]
Something to bear in mind or Android: all resources, like fonts, must be named with an camel or snake case.

**Comment by JamieB-gu** [comment]
Does that mean something like `GHGuardianHeadline-Black.ttf` wouldn't work? It would have to be renamed to `GHGuardianHeadlineBlack.ttf`?

**Comment by JamieB-gu** [comment]
@jordanterry ?

**Comment by jordanterry** [comment]
@JamieB-gu sorry! Yes, you'd have to rename it to that or add underscores if separating words is important.

**Comment by JamieB-gu** [comment]
@jordanterry Based on [this snippet](https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml#using-support-lib) from the docs it looks like dashes _are_ supported... am I reading that correctly?

**Comment by jordanterry** [comment]
We spoke about this offline but I think it would be worth rewriting here for posterity. 

Android [resources](https://developer.android.com/reference/android/content/res/Resources) (fonts are a resource) are referenced in the app via the `R` class. 

This is a generated class that provides us with a concrete reference to a file resource in Java and Kotlin. To be able to reference a resource from Java or Kotlin the file name must conform to the rules of a Java identifier (can be found in this [link](https://docs.oracle.com/cd/E19798-01/821-1841/bnbuk/index.html)). A hyphen isn't a valid character for an identifier and will cause a compiler error:

```
'-' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
```

I believe the example in the snippet is above and will log a bug on the Google issue tracker.

**Comment by jordanterry** [comment]
In an effort to clean up the confusion I've submitted a bug to Google: https://issuetracker.google.com/issues/150808982

**Comment by alexanderedge** [comment]
Looks good from my perspective. We just need to be careful that we don't just drop in the plist the first time and lose some fonts.

**Comment by JamieB-gu** [comment]
cc @paperboyo

**Comment by paperboyo** [comment]
Thanks! Fucking hell :-(. This is dumb. So… since there is no way we’ll get internal Postscript names for our fonts changed, and they do contain hyphens as they are legal per spec, this would suggest them synced to filename is a no-no for Android even though it’s a requirement for React Native and is successfully used like that in [Daily Edition](https://github.com/guardian/editions/tree/master/projects/Mallard/src/assets/fonts)?

Android would have to invent it’s own workaround for this, then. Unfortunate, that it will be inconsistent with the rest of the estate as this always eventually lead to assets being out of date :-(.

This should be taken care of dev environment or something, says the naive one.

**Comment by JamieB-gu** [comment]
I think Fontastique can take care of this. I'm currently hoping that for the native apps we'll offer a zip file of the fonts they've selected. So we just need to change the filenames on the fly for the Android download.

The other platforms, like web and iOS, don't have to care about this, they'll get the files with the original filename.

**Comment by paperboyo** [comment]
I wonder how Google Fonts deals with this as their fonts use hyphens like everyone else?
![image](https://user-images.githubusercontent.com/6032869/75990964-9cd9c900-5eed-11ea-9c72-915e0de9ba7c.png)

**Comment by JamieB-gu** [comment]
Been looking into iOS support.

- [ ] Names of the font files go into `Info.plist`; they form an `array` under the key `UIAppFonts`

From there, the fonts are available in code via their [PostScript name](https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app#2939906). Perhaps we should provide a text file with the download that lists all the PostScript names and optionally their corresponding file names.

**Comment by paperboyo** [comment]
PostScript names are (should be!) identical to filenames.

**Comment by JamieB-gu** [comment]
Good point @paperboyo. Ok so maybe when we implement Fontastique this won't be an issue because file names will be in sync with PS names (I don't they currently match in the iOS app).

**Comment by SLambrakis** [comment]
👍 To all above from an iOS perspective.
