### ISSUE TITLE
"Context" View

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/fontastique#7]
We currently have a simple list of all the fonts. Would it also be valuable to add a "context" view, where the fonts are grouped by their family and recommended use on the site (headings, body copy etc.)?

**Comment by paperboyo** [comment]
> recommended use on the site

Design System page provides (should provide) that? cc @SiAdcock

**Comment by JamieB-gu** [comment]
If that's the case, we should link users there from this tool for more information.
